### ISSUE TITLE
Getting everyone on board 

### ISSUE THREAD

**Issue by perpetualjourney** [ImperialEntrepreneurs/Wiki#1]
This is an issue to track the adoption of github as our new shiny content and knowledge manager.

TODO FOR EVERYONE:
- Create a free github account here: [Join Github](https://github.com/join)
- Comment below and I will add you to the organisation
- Add your info to this [page](https://github.com/ImperialEntrepreneurs/Wiki/wiki/Team-Members-Info)
- Create or update the page for the event you manage (If any)
- Tick the box below next to your name
- Enjoy the freedom of real organisation :sunglasses: 

You can reach me all day (8th Jan) on my mobile 07869770156 if you need spiritual guidance.

People that are yet to sign up (please tick the box when you've done al of the above):
- [ ] Jag Jill
- [ ] James Soo
- [ ] Michie Takeuchi
- [ ] Vyas Iyer
- [ ] Nikolay Nikolov
- [ ] Raymond Zhan
- [ ] Alia Sheikh
- [ ] Rabeet Khan
- [ ] Vlad Podgurschi
- [ ] Jack Yang
- [ ] Tanja

**Comment by J-Gill** [comment]
Cool, add me to the organisation.

**Comment by perpetualjourney** [comment]
@J-Gill done! accept the invitation here: https://github.com/ImperialEntrepreneurs/

**Comment by perpetualjourney** [comment]
@ImperialEntrepreneurs/icentrepreneurs please tick the box next to your name above when you think you're done!

**Comment by tmuetze** [comment]
Nice one! Thanks for setting this up! But you forgot to create a box for me :(

**Comment by tmuetze** [comment]
Nice one! Thanks for setting this up :) but you forgot to add me to the boxes above :(

**Comment by perpetualjourney** [comment]
@tmuetze Sorry dear, I've updated the issue now!
