### ISSUE TITLE
Refreshers Fair rota

### ISSUE THREAD

**Issue by perpetualjourney** [ImperialEntrepreneurs/Wiki#6]
Wednesday 28th January 2015 -- 10am - 5pm
===================================
Please comment below with your availability, and what you would like to do!

Also, if we need material to be designed for the fair, please create a new issue, and assign me (@perpetualjourney) to it. Make sure to reference this issue by writing a `#6` in the body.

Let's get going guys :)

**Comment by tmuetze** [comment]
Until now, my schedule is pretty empty. I would prefer a morning shift but am quite flexible until now.
